project:
  type: website

format:
  html:
    theme:
      light:
        - flatly
        - ./stylesheets/flatly.scss
      dark:
        - darkly
        - ./stylesheets/darkly.scss
    highlight-style:
      light: ./stylesheets/material-light.theme
      dark: ./stylesheets/material-dark.theme
    css:
      - ./stylesheets/zensical.min.css
      - ./stylesheets/palette.min.css
      - ./stylesheets/chickenstats.css
    include-after-body: stylesheets/md-scheme-sync.html
    toc: true
    toc-location: right
    keep-md: true
    page-layout: full
  commonmark: default

website:
  title: "chickenstats-blog"
  favicon: images/site/logos/favicon.png
  site-url: https://blog.chickenstats.com
  google-analytics: "G-65XFF92N5R"
  twitter-card: true
  open-graph: true
  navbar:
    background: light
    search: true
    logo: images/site/logos/favicon.png
    title: "chickenstats-blog"
    pinned: true
    sticky: true
    collapse-below: md
    left:
      - text: "docs"
        href: https://chickenstats.com/
      - text: "about"
        href: about.qmd
      - text: "blog"
        href: blog/index.qmd
      - text: "projects"
        href: projects.ipynb
    right:
      - icon: github
        href: "https://github.com/chickenstats/chickenstats-blog"
  cookie-consent:
    type: express
    style: interstitial
  page-footer:
    left: Copyright &copy; 2025-26 chicken and stats
    right:
      - icon: github
        href: "https://github.com/chickenstats/chickenstats-blog"
      - icon: bluesky
        href: "https://bsky.app/profile/chickenandstats.com"

metadata-files: [nbdev.yml, sidebar.yml]

execute:
  freeze: auto
